version: '3.8'

services:
  api:
    build: .
    command: >
      bash -c "alembic upgrade head
      && uvicorn app.main:app --host 0.0.0.0"
    ports:
      - 8008:8000
    depends_on:
      - pgsql_db

  pgsql_db:
    image: postgres:13-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./env/.prod.env

volumes:
  pgdata:
